steps:

  # downloads the Android toolchain
  - label: ':docker: Build Android base image'
    key: "android-common"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          build:
            - android-common
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest
      - docker-compose#v3.7.0:
          push:
            - android-common:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:latest

  # assembles the bugsnag-android SDK
  - label: ':docker: Build Android base CI image'
    key: "android-ci"
    depends_on: "android-common"
    timeout_in_minutes: 30
    plugins:
      - docker-compose#v3.7.0:
          build:
            - android-ci
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/android
          cache-from:
            - android-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-${BRANCH_NAME}
      - docker-compose#v3.7.0:
          push:
            - android-ci:855461928731.dkr.ecr.us-west-1.amazonaws.com/android:ci-${BRANCH_NAME}

  - label: ':android: Build fixture APK r21'
    key: "fixture-r21"
    depends_on: "android-ci"
    timeout_in_minutes: 30
    artifact_paths: build/release/fixture-r21.apk
    plugins:
      - docker-compose#v3.7.0:
          run: android-builder
    env:
      MAVEN_VERSION: "3.6.1"
      TEST_FIXTURE_NDK_VERSION: "21.3.6528147"
      TEST_FIXTURE_NAME: "fixture-r21.apk"
      BUILD_TASK: "assembleRelease"

  - label: ':android: Android 12 NDK r21 - Sauce Labs'
    depends_on: "fixture-r21"
    timeout_in_minutes: 120
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=sl"
          - "--device=Google_Pixel_6_real_us"
          - "--os=android"
          - "--os-version=12"
          - "--fail-fast"
    concurrency: 2
    concurrency_group: 'sauce-labs'
    concurrency_method: eager

  - label: ':android: Android 11 NDK r21 - Sauce Labs'
    depends_on: "fixture-r21"
    timeout_in_minutes: 120
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=sl"
          - "--device=Google_Pixel_3_real_us1"
          - "--os=android"
          - "--os-version=11"
          - "--fail-fast"
    concurrency: 2
    concurrency_group: 'sauce-labs'
    concurrency_method: eager

  - label: ':android: Android 10 NDK r21 - Sauce Labs'
    depends_on: "fixture-r21"
    timeout_in_minutes: 120
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=sl"
          - "--device=Google_Pixel_3a_XL_real"
          - "--os=android"
          - "--os-version=10"
          - "--fail-fast"
    concurrency: 2
    concurrency_group: 'sauce-labs'
    concurrency_method: eager

  - label: ':android: Android 9 NDK r21 - Sauce Labs'
    depends_on: "fixture-r21"
    timeout_in_minutes: 120
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=sl"
          - "--device=Motorola_Moto_G7_real"
          - "--os=android"
          - "--os-version=9"
          - "--fail-fast"
    concurrency: 2
    concurrency_group: 'sauce-labs'
    concurrency_method: eager

  - label: ':android: Android 8 NDK r21 - Sauce Labs'
    depends_on: "fixture-r21"
    timeout_in_minutes: 120
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=sl"
          - "--device=Motorola_Moto_G5_Plus_real"
          - "--os=android"
          - "--os-version=8"
          - "--fail-fast"
    concurrency: 2
    concurrency_group: 'sauce-labs'
    concurrency_method: eager

  - label: ':android: Android 7 NDK r21 - Sauce Labs'
    depends_on: "fixture-r21"
    timeout_in_minutes: 120
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=sl"
          - "--device=Motorola_Moto_X_Play_real"
          - "--os=android"
          - "--os-version=7"
          - "--fail-fast"
    concurrency: 2
    concurrency_group: 'sauce-labs'
    concurrency_method: eager

  - label: ':android: Android 6 NDK r21 - Sauce Labs'
    depends_on: "fixture-r21"
    timeout_in_minutes: 120
    plugins:
      artifacts#v1.2.0:
        download: "build/release/fixture-r21.apk"
        upload: "maze_output/failed/**/*"
      docker-compose#v3.7.0:
        pull: android-maze-runner
        run: android-maze-runner
        command:
          - "features/full_tests"
          - "--app=/app/build/release/fixture-r21.apk"
          - "--farm=sl"
          - "--device=Samsung_Galaxy_J7_real_us"
          - "--os=android"
          - "--os-version=6"
          - "--fail-fast"
    concurrency: 2
    concurrency_group: 'sauce-labs'
    concurrency_method: eager

